### PR TITLE
Proxy videos folder

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by hexylena** [comment]
Needed for galaxyproject/training-material#2040

**Comment by hexylena** [comment]
Could anyone merge this? Our subtitles are broken until it is :( 

If you don't want to proxy the video, then, we can update for just the subtitles? Please let me know :)

**Comment by natefoo** [comment]
Sorry for the wait ;(

**Comment by hexylena** [comment]
No dramas! :)

**Pull request merged**
