### PR TITLE
Add curl package to Jenkins slaves.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by natefoo** [comment]
@jmchilton try: `ansible-playbook -i galaxyenv/inventory galaxyenv/playbook.yml --limit=jenkinsslaves --ask-vault-pass` and let me know how it goes.

**Comment by jmchilton** [comment]
@natefoo

```
(ansible-venv)jmchilton@scofield:~/infrastructure-playbook $ ansible-playbook -i galaxyenv/inventory galaxyenv/playbook.yml --limit=jenkinsslaves --ask-vault-pass
Vault password: 
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure 
become_method is 'sudo' (default).
This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [Tasks for "base environment" hosts] **************************************

TASK [setup] *******************************************************************
fatal: [n6.galaxyproject.org]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [n4.galaxyproject.org]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
        to retry, use: --limit @/afs/galaxyproject.org/user/jmchilton/infrastructure-playbook/galaxyenv/playbook.retry

PLAY RECAP *********************************************************************
n4.galaxyproject.org       : ok=0    changed=0    unreachable=1    failed=0   
n6.galaxyproject.org       : ok=0    changed=0    unreachable=1    failed=0   
```

But I can ssh now that I setup that forward agent stuff appropriately. Any thoughts?

**Comment by natefoo** [comment]
Were you able to run this with:

```console
% export ANSIBLE_SSH_CONTROL_PATH=`mktemp -d --tmpdir "ansible-cp-$USER.XXXXXXXX"\`
```

?

**Comment by jmchilton** [comment]
Yes I was - thanks @natefoo.

**Pull request merged**
